---
galaxy_info:
  author: Leslie-Alexandre DENIS
  description: group, user, ssh keys management
  license: MIT
  min_ansible_version: 2.7
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - system
dependencies: []
