---

sshd_listen:
  address: "0.0.0.0"
  port: "22"

sshd_config:
  print_motd: "no"
  x11_forwarding: "no"
  log:
    level: VERBOSE
    facility: AUTH

sshd_security:
  auth:
    methods: publickey
    publickey: "yes"
    root: "no"
  algorithms:
    keyx:
      "curve25519-sha256@libssh.org,ecdh-sha2-nistp521,\
      ecdh-sha2-nistp384,ecdh-sha2-nistp256,\
      diffie-hellman-group-exchange-sha256"
    ciphers:
      "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,\
      aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
    mac:
      "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,\
      umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"

sshd_allowed:
  user: root
  group: root
